apiVersion: v1
kind: Service
metadata:
  name: retailops-frontend
  namespace: retailops
  labels:
    app.kubernetes.io/name: retailops-frontend
    app.kubernetes.io/part-of: retailops-platform
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: retailops-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
