apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: retailops
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: retailops-platform
    app.kubernetes.io/component: database
    retailops.io/environment: dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
