apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: retailops-runtime-secrets
  namespace: retailops
  labels:
    app.kubernetes.io/name: retailops-runtime-secrets
    app.kubernetes.io/part-of: retailops-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: retailops-aws-secrets-manager
    kind: SecretStore
  target:
    name: retailops-runtime-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: retailops/dev/runtime
        property: DATABASE_URL
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: retailops/dev/runtime
        property: POSTGRES_PASSWORD
