apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: retailops-aws-secrets-manager
  namespace: retailops
  labels:
    app.kubernetes.io/name: retailops-external-secrets
    app.kubernetes.io/part-of: retailops-platform
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
