apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/retailops.yaml
  - config/app-config.yaml
  - api/deployment.yaml
  - api/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml
